### ISSUE TITLE
data loading in your fixmatch

### ISSUE THREAD

**Issue by jizhang02** [urchade/semi-supervised-learning#2]
Hello, 

thank you for sharing your code. Just I got confused in your code.
![image](https://github.com/urchade/semi-supervised-learning/assets/46089068/edb157b6-859e-4b29-8664-4262601349cd)
In your for loop, 
`for batch_sup in pbar:`, why do you set labeled data? if there are 50 labeled images, 500 unlabeled images, but in this way, can all the 500 unlabeled images finish training?

again, if there are 100 labeled images, 50 unlabeled images, then the 50 unlabeled images will be trained twice?

I don't understand very well about this part, could you explain for that?

Thank you very much!

All the best,
Jing

**Comment by urchade** [comment]
Hi Jing, 
"if there are 100 labeled images, 50 unlabeled images, then the 50 unlabeled images will be trained twice?" => the answer is yes

"if there are 50 labeled images, 500 unlabeled images, but in this way, can all the 500 unlabeled images finish training?"
=> you can set iterator for the supervised loader and have num_steps variable to decide that


````python
sup_iter = iter(sup_loader)
unsup_iter = iter(unsup_loader)

num_steps = 1000

for step in range(num_steps):

    # zero the model gradients
    model.zero_grad()

    # get next batch of supervised data
    try:
        batch_sup = next(sup_iter)
    except StopIteration:
        # if we've run out of data, reinitialize the iterator
        sup_iter = iter(sup_loader)
        batch_sup = next(sup_iter)

    # get supervised data
    x_sup, y = batch_sup
    x_sup, y = x_sup.to(device), y.to(device)

    # get next batch of unsupervised data
    try:
        x_weak, x_strong = next(unsup_iter)
    except StopIteration:
        # if we've run out of data, reinitialize the iterator
        unsup_iter = iter(unsup_loader)
        x_weak, x_strong = next(unsup_iter)

    # ... rest of your training loop ...
```

tell if you have another question.

Urchade

**Comment by jizhang02** [comment]
Hi Urchade,

Thank you for your reply, it's much clearer!

For the data loading, I did it in another way,  both works.

```
for epoch in range(num_epochs):
        train_losses = []
        model.train()

        for labeled_data, unlabeled_data in zip(labeled_loader, unlabeled_loader):
            x1, gt = labeled_data
            wx2, sx2 = unlabeled_data
            x1, gt = x1.cuda(), gt.cuda()
            wx2, sx2 = wx2.cuda(), sx2.cuda()
            with torch.enable_grad():
            ...                
```

Greetings!

Jing
